version: '3'
services:
  api:
    image: milleria-api
    build: .
    environment:
      - VIRTUAL_HOST=api.milleria.org,api.wompupthejams.com
    networks:
      - backend
    ports:
      - "3030:3030"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: milleria-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
